// src/components/SocialBar.vue
<script setup lang="ts">
import { socialBarData } from '@/data/social-bar'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
</script>

<template>
  <ul class="flex flex-row gap-4">
    <li v-for="social in socialBarData" :key="social.name">
      <a
        :href="social.link"
        target="_blank"
        rel="noopener noreferrer"
        :aria-label="social.name + ' ' + social.link"
        :data-umami-event="'Social link clicked: ' + social.name"
        class="text-xl opacity-60 transition-all duration-200 ease-in-out hover:text-theme-950 hover:opacity-100 hover:dark:text-theme-50"
      >
        <FontAwesomeIcon :icon="social.icon" :aria-label="social.name + ' icon'" />
      </a>
    </li>
  </ul>
</template>

// src/components/SocialBar.tsx
import {
  IconDefinition,
  faGithub,
  faInstagram,
  faLinkedinIn,
} from "@fortawesome/free-brands-svg-icons";
import { faEnvelope } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Link from "next/link";

const contactContent: {
  name: string;
  link: string;
  icon: IconDefinition;
}[] = [
  {
    name: "Github",
    link: "https://github.com/martinmiglio",
    icon: faGithub,
  },
  {
    name: "Email",
    link: "mailto:contact@martinmiglio.dev",
    icon: faEnvelope,
  },
  {
    name: "LinkedIn",
    link: "https://www.linkedin.com/in/martinmiglio",
    icon: faLinkedinIn,
  },
  {
    name: "Instagram",
    link: "https://www.instagram.com/migliosights",
    icon: faInstagram,
  },
];

export default function SocialBar() {
  return (
    <div className="flex flex-row gap-4">
      {contactContent.map((item) => (
        <Link
          href={item.link}
          key={item.link}
          aria-label={`${item.name} link`}
          data-umami-event={`Social link clicked: ${item.name}`}
        >
          <FontAwesomeIcon
            icon={item.icon}
            aria-label={`${item.name} icon`}
            className="h-5 w-5 opacity-60 transition-all duration-200 ease-in-out hover:text-theme-950 hover:opacity-100 hover:dark:text-theme-50"
          />
        </Link>
      ))}
    </div>
  );
}
